% --- BASE DE DONNÉES (Faits) ---
vol(af442, cdg, gig, 1300, 1900). [cite: 1]
vol(af100, cdg, lhr, 0800, 1000).
vol(ba200, lhr, jfk, 1400, 2200).
vol(ua300, jfk, lax, 2300, 0400).

% Ajout des aéroports pour lier les codes aux villes 
aeroport(cdg, france, paris, charles_de_gaulle). [cite: 5]
aeroport(gig, bresil, rio, galeao). [cite: 5]
aeroport(lhr, uk, londres, heathrow). [cite: 5]
aeroport(jfk, usa, new_york, john_f_kennedy). [cite: 5]
aeroport(lax, usa, los_angeles, los_angeles_intl). [cite: 5]